import { useState } from "react";
import { Link } from "wouter";
import AppShell from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowRight, Bot, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, HeartPulse, ListChecks, MessageCircle, ShieldCheck, Utensils } from "lucide-react";

const profile = { name:"Alya", ageMonths:18, allergy:"", budget:20000, region:"Jawa Barat" };

export default function Home(){
  const overview = trpc.dashboard.overview.useQuery(profile);
  const [tasks,setTasks]=useState([false,true,false]);
  const [question,setQuestion]=useState("Alya sedang susah makan sayur, apa langkah kecil yang bisa dicoba?");
  const coach=trpc.agent.coach.useMutation();
  const data=overview.data;
  const toggle=(index:number)=>setTasks(current=>current.map((v,i)=>i===index?!v:v));
  return <AppShell title="Beranda keluarga" subtitle="Ringkasan tindakan paling penting untuk Alya hari ini">
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <div className="relative min-h-[290px] overflow-hidden rounded-[30px] bg-[#164739] p-6 text-white shadow-[0_20px_50px_rgba(21,68,51,.15)] sm:p-8"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#55b77e]/20 blur-2xl"/><div className="relative z-10 max-w-xl"><p className="text-sm font-medium text-[#9ddcb3]">Ringkasan hari ini</p><h2 className="mt-6 text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-4xl">Selamat pagi, Bunda.<br/>Alya punya <span className="font-serif italic text-[#bceecb]">3 langkah sederhana</span> hari ini.</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#bdd4c7]">Agent telah memeriksa profil, rencana makan, dan catatan pertumbuhan. Tidak ada peringatan baru.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/rencana"><Button className="rounded-full bg-[#b9efcb] px-6 text-[#143e32] hover:bg-[#d0f7db]">Lihat rencana hari ini <ArrowRight size={16} className="ml-2"/></Button></Link><Link href="/agent-center"><Button variant="outline" className="rounded-full border-white/20 bg-white/5 px-6 text-white hover:bg-white/10 hover:text-white">Lihat kerja agent</Button></Link></div></div><div className="absolute bottom-0 right-2 hidden h-[250px] w-[310px] opacity-20 xl:block"><div className="absolute bottom-10 right-14 h-32 w-32 rounded-full border-[22px] border-[#bceecb]"/><div className="absolute bottom-20 right-2 h-20 w-20 rounded-full border-[16px] border-[#e9c88f]"/></div></div>
      <Card className="border-[#dfe8df] bg-white shadow-[0_12px_30px_rgba(35,73,49,.06)]"><CardHeader className="pb-3"><div className="flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-[#7a9083]">Kesiapan hari ini</p><CardTitle className="mt-2 text-3xl">{data?.completion ?? 72}%</CardTitle></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e5f4e8] text-[#208255]"><ListChecks/></div></div></CardHeader><CardContent><div className="h-2.5 overflow-hidden rounded-full bg-[#e5eee6]"><div className="h-full w-[72%] rounded-full bg-[#35a76a]"/></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f7f9f5] p-4"><p className="text-2xl font-semibold">{data?.streak ?? 6}</p><p className="mt-1 text-xs text-[#74887d]">hari rutin tercatat</p></div><div className="rounded-2xl bg-[#fff8e9] p-4"><p className="text-2xl font-semibold">3</p><p className="mt-1 text-xs text-[#8a7958]">tugas sederhana</p></div></div></CardContent></Card>
    </section>

    <section className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
      <Metric icon={<Utensils/>} tone="green" label="Menu hari ini" value={data?.today?.title ?? "Menyiapkan..."} note="Lolos pemeriksaan"/>
      <Metric icon={<HeartPulse/>} tone="blue" label="Pertumbuhan" value={data?.growth.label ?? "Menganalisis..."} note="4 catatan tersedia"/>
      <Metric icon={<ShieldCheck/>} tone="amber" label="Filter keamanan" value={data?.guardrails.blocked.length ? `${data.guardrails.blocked.length} diblokir` : "Tidak ada risiko"} note="Diperiksa 08.15 WIB"/>
      <Metric icon={<CircleDollarSign/>} tone="purple" label="Batas harian" value={`Rp${profile.budget.toLocaleString("id-ID")}`} note="Rencana menyesuaikan"/>
    </section>

    <section className="mt-6 grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <Card className="border-[#dfe8df] shadow-none"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-xl">Yang perlu dilakukan</CardTitle><p className="mt-1 text-sm text-[#74887d]">Cukup selesaikan satu per satu.</p></div><span className="text-xs font-medium text-[#27835a]">Hari ini</span></div></CardHeader><CardContent className="space-y-2">{(data?.tasks??[]).map((task,index)=><button key={task.id} onClick={()=>toggle(index)} className="flex w-full items-center gap-3 rounded-2xl border border-[#e3ebe3] p-4 text-left transition hover:border-[#b9d9c2] hover:bg-[#fafcf9]"><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-lg border ${tasks[index]?"border-[#2da466] bg-[#2da466] text-white":"border-[#cbd9cd] bg-white"}`}>{tasks[index]&&<Check size={14}/>}</span><div><p className={`text-sm font-medium ${tasks[index]?"text-[#84958c] line-through":""}`}>{task.label}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#83958c]"><Clock3 size={12}/>{task.time} WIB</p></div><ChevronRight className="ml-auto text-[#9aaa9f]" size={17}/></button>)}</CardContent></Card>
      <Card className="overflow-hidden border-[#dfe8df] shadow-none"><div className="grid sm:grid-cols-[.8fr_1.2fr]"><img src="/manus-storage/nutrishield-local-meal_bb9a48a3.jpg" alt="Menu lokal hari ini" className="h-full min-h-[250px] w-full object-cover"/><div className="p-6"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[#25835a]"><CalendarDays size={15}/> Pilihan agent</div><h3 className="mt-4 text-2xl font-semibold leading-tight">{data?.today?.title ?? "Nasi tim kembung kelor"}</h3><p className="mt-3 text-sm leading-6 text-[#71867a]">Tekstur {data?.today?.texture?.toLowerCase() ?? "lumat lembut"}, memakai bahan yang mudah ditemukan di sekitar Jawa Barat.</p><div className="mt-5 flex items-center justify-between border-y border-[#e5ece5] py-3 text-sm"><span className="text-[#72867b]">Perkiraan</span><strong>Rp{(data?.today?.estimate??12000).toLocaleString("id-ID")}</strong></div><Link href="/rencana"><Button variant="link" className="mt-3 px-0 text-[#1f7d54]">Buka cara memasak <ArrowRight size={15} className="ml-2"/></Button></Link></div></div></Card>
    </section>

    <section className="mt-6 grid gap-5 xl:grid-cols-[1.18fr_.82fr]">
      <Card className="border-[#dfe8df] shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e4f1ff] text-[#2d77b7]"><Bot size={20}/></div><div><CardTitle className="text-xl">Tanya NutriShield</CardTitle><p className="text-sm text-[#74887d]">AI menjawab setelah aturan keselamatan selesai.</p></div></div></CardHeader><CardContent><div className="rounded-2xl border border-[#dce7dd] bg-[#fbfcfa] p-2"><textarea value={question} onChange={e=>setQuestion(e.target.value)} className="min-h-24 w-full resize-none bg-transparent p-3 text-sm leading-6 outline-none"/><div className="flex justify-end"><Button onClick={()=>coach.mutate({...profile,question})} disabled={coach.isPending} className="rounded-xl bg-[#173f34]">{coach.isPending?"Sedang memeriksa...":"Tanyakan"}<MessageCircle size={15} className="ml-2"/></Button></div></div>{coach.data&&<div className="mt-4 rounded-2xl bg-[#eff7f0] p-4 text-sm leading-6 text-[#365f4d]"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-[#208056]"><ShieldCheck size={14}/> {coach.data.checkedFoods} bahan diperiksa sebelum jawaban</div>{coach.data.answer}</div>}</CardContent></Card>
      <Card className="border-[#dfe8df] bg-[#fff9ea] shadow-none"><CardHeader><CardTitle className="text-xl">Catatan untuk keluarga</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-[#766848]">Pertumbuhan Alya terlihat bergerak positif. Fokus minggu ini bukan mencari menu sempurna, tetapi menjaga protein hewani hadir secara rutin dan mencatat apa yang benar-benar dimakan.</p><div className="mt-5 rounded-2xl bg-white/70 p-4"><p className="text-xs text-[#8a7a58]">Jadwal Posyandu berikutnya</p><p className="mt-1 font-semibold">Sabtu, 26 September · 08.00</p></div></CardContent></Card>
    </section>
  </AppShell>;
}

function Metric({icon,tone,label,value,note}:{icon:React.ReactNode;tone:"green"|"blue"|"amber"|"purple";label:string;value:string;note:string}){const colors={green:"bg-[#e4f4e8] text-[#208255]",blue:"bg-[#e6f2fc] text-[#2878b9]",amber:"bg-[#fff2db] text-[#b2781e]",purple:"bg-[#f0eafb] text-[#7753ad]"};return <Card className="border-[#dfe8df] shadow-none"><CardContent className="p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${colors[tone]}`}>{icon}</div><p className="mt-5 text-xs text-[#7b8e83]">{label}</p><p className="mt-1 min-h-12 text-lg font-semibold leading-6">{value}</p><p className="mt-2 text-[11px] text-[#8b9b92]">{note}</p></CardContent></Card>}
