import { Link } from "wouter";
import { ArrowRight, Bot, Check, Database, HeartPulse, Menu, Play, ShieldCheck, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";

const steps = [
  { no:"01", title:"Memahami keluarga", text:"Membaca usia, alergi, wilayah, anggaran, serta riwayat pertumbuhan anak." },
  { no:"02", title:"Menyaring risiko", text:"Aturan deterministik bekerja sebelum AI menyusun saran atau menu." },
  { no:"03", title:"Menyusun tindakan", text:"Agent membuat rencana sederhana, memantau progres, dan menjelaskan alasannya." },
  { no:"04", title:"Menaikkan perhatian", text:"Ketika pola perlu diperiksa, keluarga mendapat ringkasan untuk dibawa ke Posyandu." },
];

export default function Landing(){return <div className="min-h-screen bg-[#fbfcf8] text-[#153a2f]">
  <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-[1380px] items-center px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#173f34] text-[#bceecb]"><ShieldCheck size={24}/></div><div><p className="font-semibold tracking-tight">NutriShield</p><p className="text-[10px] uppercase tracking-[.18em] text-[#667c70]">Family Intelligence</p></div></Link><nav className="ml-auto hidden items-center gap-8 text-sm text-[#526c60] md:flex"><a href="#cara-kerja">Cara kerja</a><a href="#fitur">Fitur</a><a href="#keamanan">Keamanan</a></nav><Link href="/app" className="ml-6 hidden sm:block"><Button className="rounded-full bg-[#173f34] px-6 text-white hover:bg-[#225647]">Coba aplikasi <ArrowRight size={16} className="ml-2"/></Button></Link><Menu className="ml-auto sm:hidden"/></div></header>
  <main>
    <section className="relative min-h-[790px] overflow-hidden bg-[#eef5ea]"><img src="/manus-storage/nutrishield-hero-family_8a162b14.jpg" alt="Ibu dan anak menyiapkan makanan lokal bergizi" className="absolute inset-0 h-full w-full object-cover object-[62%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-[#eff5eb] via-[#eff5eb]/95 via-45% to-transparent"/><div className="relative mx-auto flex min-h-[790px] max-w-[1380px] items-center px-5 pt-24 sm:px-8"><div className="max-w-[660px]"><p className="text-sm font-medium text-[#1d7952]">Pendamping keluarga dengan agent AI yang dapat diaudit</p><h1 className="mt-7 text-[46px] font-semibold leading-[1.04] tracking-[-.055em] sm:text-[64px] lg:text-[76px]">Tumbuh sehat,<br/><span className="font-serif italic text-[#24855a]">tanpa menebak.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#526e61] sm:text-lg">NutriShield membantu keluarga memilih pangan lokal, memantau pertumbuhan, dan memahami langkah berikutnya—dengan aturan keselamatan yang bekerja sebelum AI menjawab.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/app"><Button size="lg" className="h-13 rounded-full bg-[#173f34] px-7 text-white hover:bg-[#225647]">Masuk ke dashboard <ArrowRight size={17} className="ml-2"/></Button></Link><a href="#cara-kerja"><Button size="lg" variant="outline" className="h-13 rounded-full border-[#b7cdbd] bg-white/70 px-7"><Play size={16} className="mr-2 fill-current"/> Lihat cara kerja</Button></a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs text-[#5f766b]"><span className="flex items-center gap-2"><Check size={15} className="text-[#278d5e]"/> Pangan pasar lokal</span><span className="flex items-center gap-2"><Check size={15} className="text-[#278d5e]"/> Jejak keputusan transparan</span><span className="flex items-center gap-2"><Check size={15} className="text-[#278d5e]"/> Bahasa mudah dipahami</span></div></div></div><div className="absolute bottom-5 right-5 hidden w-[310px] rounded-3xl border border-white/50 bg-white/80 p-5 shadow-[0_20px_60px_rgba(25,65,46,.16)] backdrop-blur-xl lg:block"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e3f4e7] text-[#1d8155]"><Bot size={20}/></div><div><p className="text-sm font-semibold">Agent baru selesai bekerja</p><p className="mt-1 text-xs leading-5 text-[#698075]">4 bahan diperiksa · 7 menu disusun · tidak ada risiko baru</p></div></div><div className="mt-4 flex items-center justify-between border-t border-[#dae6dc] pt-3 text-[11px] text-[#72877c]"><span>NS-20260916-2184</span><span className="text-[#218258]">1,8 detik</span></div></div></section>
    <section className="border-y border-[#e2ebe2] bg-white"><div className="mx-auto grid max-w-[1250px] grid-cols-2 gap-6 px-5 py-8 sm:grid-cols-4 sm:px-8"><div><p className="text-3xl font-semibold tracking-tight">1.646</p><p className="mt-1 text-xs text-[#70857a]">record pangan bersumber</p></div><div><p className="text-3xl font-semibold tracking-tight">5</p><p className="mt-1 text-xs text-[#70857a]">peran agent khusus</p></div><div><p className="text-3xl font-semibold tracking-tight">7 hari</p><p className="mt-1 text-xs text-[#70857a]">rencana sekali jalan</p></div><div><p className="text-3xl font-semibold tracking-tight">100%</p><p className="mt-1 text-xs text-[#70857a]">jejak proses terlihat</p></div></div></section>
    <section id="cara-kerja" className="mx-auto max-w-[1250px] px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#27875b]">Bukan chatbot biasa</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.04em]">AI yang bekerja,<br/>bukan sekadar menjawab.</h2><p className="mt-5 text-sm leading-7 text-[#667d71]">Setiap rekomendasi melewati rangkaian agent khusus. Pengguna dapat membuka jejak kerja dan melihat apa yang diperiksa, diblokir, atau diteruskan.</p></div><div className="grid gap-px overflow-hidden rounded-[28px] border border-[#dfe9df] bg-[#dfe9df] sm:grid-cols-2">{steps.map(step=><div key={step.no} className="bg-white p-7"><span className="font-mono text-xs text-[#69a782]">{step.no}</span><h3 className="mt-8 text-lg font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-6 text-[#6b8176]">{step.text}</p></div>)}</div></div></section>
    <section id="fitur" className="bg-[#123f33] py-24 text-white"><div className="mx-auto max-w-[1250px] px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8dd2a7]">Satu rumah untuk kebutuhan keluarga</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.04em]">Dari dapur hari ini sampai kunjungan Posyandu berikutnya.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Feature icon={<HeartPulse/>} title="Growth Sentinel" text="Melihat arah perubahan berat dan tinggi, lalu menyiapkan ringkasan tindak lanjut."/><Feature icon={<Database/>} title="Local Food Planner" text="Menyusun menu lokal 7 hari sesuai alergi, wilayah, tekstur, dan batas biaya."/><Feature icon={<UsersRound/>} title="Mode keluarga & kader" text="Tampilan sederhana untuk orang tua, dengan jejak lebih rinci bagi kader pendamping."/></div></div></section>
    <section id="keamanan" className="mx-auto max-w-[1250px] px-5 py-24 sm:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><img src="/manus-storage/nutrishield-local-meal_bb9a48a3.jpg" alt="Bahan makanan lokal ramah anak" className="aspect-[4/3] w-full rounded-[32px] object-cover shadow-[0_24px_70px_rgba(30,73,50,.13)]"/><div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e3f4e7] text-[#207c54]"><ShieldCheck/></div><h2 className="mt-6 text-4xl font-semibold leading-tight tracking-[-.04em]">Keputusan AI dibatasi oleh aturan yang bisa diperiksa.</h2><p className="mt-5 text-sm leading-7 text-[#667d71]">NutriShield tidak menjanjikan “nol salah”. Yang kami bangun adalah sistem yang memisahkan fakta, aturan, dan bahasa AI—serta jujur ketika data belum cukup.</p><Link href="/sumber-data"><Button variant="link" className="mt-5 px-0 text-[#1c7d53]">Buka sumber dan batasan data <ArrowRight size={16} className="ml-2"/></Button></Link></div></div></section>
  </main><footer className="border-t border-[#e1e9e1] px-5 py-8 text-center text-xs text-[#71847a]">NutriShield Agent · Prototipe sandbox · Tidak menggantikan tenaga kesehatan</footer>
</div>}

function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-[26px] border border-white/10 bg-white/[.06] p-7"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#b9efcb] text-[#123f33]">{icon}</div><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#b9d2c4]">{text}</p></div>}
