from pathlib import Path
import re

src = Path(__file__).with_name('schema.sql').read_text()
# Remove SQLite-only pragmas, STRICT/WITHOUT ROWID, FTS virtual table and triggers.
s = re.sub(r'^PRAGMA[^;]+;\s*', '', src, flags=re.M)
s = re.sub(r'CREATE VIRTUAL TABLE IF NOT EXISTS food_search_fts.*?;\s*', '', s, flags=re.S | re.I)
s = re.sub(r'CREATE TRIGGER IF NOT EXISTS.*?END;\s*', '', s, flags=re.S | re.I)
s = s.replace(') STRICT, WITHOUT ROWID;', ');').replace(') STRICT;', ');')
s = re.sub(r'\bBLOB\b', 'BYTEA', s)
s = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', s)
s = re.sub(r'\bINTEGER PRIMARY KEY\b', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', s)
s = re.sub(r'\bINTEGER\b', 'BIGINT', s)
s = re.sub(r'\s+COLLATE NOCASE\b', '', s)
s = s.replace("metadata_json NOT NULL DEFAULT '{}'", "metadata_json NOT NULL DEFAULT '{}'")
s = s.replace("payload_json NOT NULL DEFAULT '{}'", "payload_json NOT NULL DEFAULT '{}'")
s = s.replace('CHECK(granted IN (0,1))', 'CHECK(granted IN (0,1))')
s = re.sub(r'CREATE UNIQUE INDEX IF NOT EXISTS idx_food_barcode[^;]+;', "CREATE UNIQUE INDEX IF NOT EXISTS idx_food_barcode ON canonical_foods(barcode) WHERE barcode IS NOT NULL AND barcode <> '';", s)
s = re.sub(r'CREATE INDEX IF NOT EXISTS idx_food_bpom[^;]+;', "CREATE INDEX IF NOT EXISTS idx_food_bpom ON canonical_foods(bpom_number) WHERE bpom_number IS NOT NULL AND bpom_number <> '';", s)
# SQLite trigger ownership checks become PostgreSQL constraint triggers below.
s += '''\n\nCREATE OR REPLACE FUNCTION nutrishield_check_child_owner() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n  IF NEW.child_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM child_profiles WHERE id=NEW.child_id AND user_id=NEW.user_id) THEN\n    RAISE EXCEPTION 'child ownership mismatch';\n  END IF;\n  RETURN NEW;\nEND; $$;\nDROP TRIGGER IF EXISTS consents_child_owner ON consents;\nCREATE TRIGGER consents_child_owner BEFORE INSERT OR UPDATE ON consents FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();\nDROP TRIGGER IF EXISTS jobs_child_owner ON agent_jobs;\nCREATE TRIGGER jobs_child_owner BEFORE INSERT OR UPDATE ON agent_jobs FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();\nDROP TRIGGER IF EXISTS runs_child_owner ON agent_runs;\nCREATE TRIGGER runs_child_owner BEFORE INSERT OR UPDATE ON agent_runs FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();\n\nCREATE INDEX IF NOT EXISTS idx_food_search_name ON canonical_foods USING gin (to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(normalized_name,'')));\n'''
Path(__file__).with_name('schema.postgres.sql').write_text(s)
print('wrote schema.postgres.sql', len(s), 'bytes')
