CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL CHECK(length(display_name) BETWEEN 1 AND 120),
    password_salt BYTEA NOT NULL CHECK(length(password_salt) >= 16),
    password_hash BYTEA NOT NULL CHECK(length(password_hash) = 32),
    password_iterations BIGINT NOT NULL CHECK(password_iterations >= 210000),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    disabled_at TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    token_hash BYTEA PRIMARY KEY CHECK(length(token_hash) = 32),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    user_agent TEXT,
    ip_hint TEXT,
    revoked_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_expiry ON sessions(user_id, expires_at);

CREATE TABLE IF NOT EXISTS child_profiles (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 120),
    birth_date TEXT,
    sex TEXT CHECK(sex IS NULL OR sex IN ('female','male','unspecified')),
    allergies TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_children_user ON child_profiles(user_id, created_at);

CREATE TABLE IF NOT EXISTS consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id TEXT REFERENCES child_profiles(id) ON DELETE CASCADE,
    consent_type TEXT NOT NULL CHECK(consent_type IN ('data_processing','telegram_delivery','agent_assistance')),
    granted BIGINT NOT NULL CHECK(granted IN (0,1)),
    granted_at TEXT,
    revoked_at TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(user_id, child_id, consent_type)
);

CREATE TABLE IF NOT EXISTS channel_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active_child_id TEXT REFERENCES child_profiles(id) ON DELETE SET NULL,
    provider TEXT NOT NULL CHECK(provider IN ('telegram')),
    provider_user_id TEXT NOT NULL,
    provider_chat_id TEXT NOT NULL,
    display_name TEXT,
    linked_at TEXT NOT NULL,
    unlinked_at TEXT,
    UNIQUE(provider, provider_user_id),
    UNIQUE(provider, provider_chat_id)
);

CREATE TABLE IF NOT EXISTS channel_link_codes (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id TEXT REFERENCES child_profiles(id) ON DELETE CASCADE,
    code_hash BYTEA NOT NULL UNIQUE CHECK(length(code_hash) = 32),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    consumed_by_identity_id BIGINT REFERENCES channel_identities(id),
    attempt_count BIGINT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0)
);
CREATE INDEX IF NOT EXISTS idx_link_codes_user_expiry ON channel_link_codes(user_id, expires_at);

CREATE TABLE IF NOT EXISTS measurements (
    id TEXT PRIMARY KEY,
    child_id TEXT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
    measured_at TEXT NOT NULL,
    weight_kg DOUBLE PRECISION CHECK(weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 300)),
    height_cm DOUBLE PRECISION CHECK(height_cm IS NULL OR (height_cm > 0 AND height_cm <= 250)),
    head_circumference_cm DOUBLE PRECISION CHECK(head_circumference_cm IS NULL OR (head_circumference_cm > 0 AND head_circumference_cm <= 100)),
    source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual','telegram','import')),
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    CHECK(weight_kg IS NOT NULL OR height_cm IS NOT NULL OR head_circumference_cm IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_measurements_child_time ON measurements(child_id, measured_at DESC);

CREATE TABLE IF NOT EXISTS daily_logs (
    id TEXT PRIMARY KEY,
    child_id TEXT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
    log_date TEXT NOT NULL,
    category TEXT NOT NULL CHECK(category IN ('meal','symptom','activity','sleep','note')),
    content TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE(child_id, log_date, category, content)
);

CREATE TABLE IF NOT EXISTS food_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_url TEXT,
    license TEXT,
    snapshot_path TEXT NOT NULL,
    snapshot_sha256 TEXT NOT NULL CHECK(length(snapshot_sha256) = 64),
    snapshot_bytes BIGINT NOT NULL CHECK(snapshot_bytes >= 0),
    imported_at TEXT NOT NULL,
    record_count BIGINT NOT NULL DEFAULT 0 CHECK(record_count >= 0)
);

CREATE TABLE IF NOT EXISTS normalization_runs (
    id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    policy_version TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('running','completed','failed')),
    input_manifest_json TEXT NOT NULL,
    report_json TEXT,
    error TEXT
);

CREATE TABLE IF NOT EXISTS raw_food_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES food_sources(id) ON DELETE CASCADE,
    normalization_run_id TEXT NOT NULL REFERENCES normalization_runs(id) ON DELETE CASCADE,
    source_record_id TEXT NOT NULL,
    record_type TEXT NOT NULL CHECK(record_type IN ('whole_food_index','packaged_product','bpom_listing','traditional_candidate','additive_rule','unknown')),
    payload_json TEXT NOT NULL,
    payload_sha256 TEXT NOT NULL CHECK(length(payload_sha256) = 64),
    imported_at TEXT NOT NULL,
    UNIQUE(source_id, source_record_id)
);
CREATE INDEX IF NOT EXISTS idx_raw_food_type ON raw_food_records(record_type);

CREATE TABLE IF NOT EXISTS canonical_foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    brand TEXT,
    barcode TEXT,
    bpom_number TEXT,
    record_type TEXT NOT NULL CHECK(record_type IN ('whole_food_index','packaged_product','bpom_listing','traditional_candidate','additive_rule')),
    verification_status TEXT NOT NULL,
    provenance_score DOUBLE PRECISION NOT NULL CHECK(provenance_score BETWEEN 0 AND 1),
    completeness_score DOUBLE PRECISION NOT NULL CHECK(completeness_score BETWEEN 0 AND 1),
    discovery_eligible BIGINT NOT NULL CHECK(discovery_eligible IN (0,1)),
    comparison_eligible BIGINT NOT NULL CHECK(comparison_eligible IN (0,1)),
    planning_eligible BIGINT NOT NULL CHECK(planning_eligible IN (0,1)),
    quarantined BIGINT NOT NULL DEFAULT 0 CHECK(quarantined IN (0,1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_food_normalized_name ON canonical_foods(normalized_name);
CREATE INDEX IF NOT EXISTS idx_food_eligibility ON canonical_foods(planning_eligible, discovery_eligible);
CREATE UNIQUE INDEX IF NOT EXISTS idx_food_barcode ON canonical_foods(barcode) WHERE barcode IS NOT NULL AND barcode <> '';
CREATE INDEX IF NOT EXISTS idx_food_bpom ON canonical_foods(bpom_number) WHERE bpom_number IS NOT NULL AND bpom_number <> '';

CREATE TABLE IF NOT EXISTS food_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_food_id BIGINT NOT NULL REFERENCES canonical_foods(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'id',
    UNIQUE(canonical_food_id, normalized_alias)
);
CREATE INDEX IF NOT EXISTS idx_alias_normalized ON food_aliases(normalized_alias);

CREATE TABLE IF NOT EXISTS food_source_links (
    canonical_food_id BIGINT NOT NULL REFERENCES canonical_foods(id) ON DELETE CASCADE,
    raw_food_record_id BIGINT NOT NULL UNIQUE REFERENCES raw_food_records(id) ON DELETE CASCADE,
    match_method TEXT NOT NULL CHECK(match_method IN ('source_key','barcode','bpom_number','official_code','unique_name','standalone')),
    match_confidence DOUBLE PRECISION NOT NULL CHECK(match_confidence BETWEEN 0 AND 1),
    PRIMARY KEY(canonical_food_id, raw_food_record_id)
);

CREATE TABLE IF NOT EXISTS food_nutrients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_food_id BIGINT NOT NULL REFERENCES canonical_foods(id) ON DELETE CASCADE,
    nutrient_key TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    basis TEXT NOT NULL DEFAULT '100g',
    source_raw_id BIGINT NOT NULL REFERENCES raw_food_records(id) ON DELETE CASCADE,
    UNIQUE(canonical_food_id, nutrient_key, basis, source_raw_id)
);

CREATE TABLE IF NOT EXISTS food_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_food_id BIGINT NOT NULL REFERENCES canonical_foods(id) ON DELETE CASCADE,
    amount DOUBLE PRECISION NOT NULL CHECK(amount >= 0),
    currency TEXT NOT NULL DEFAULT 'IDR',
    unit TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    source_raw_id BIGINT REFERENCES raw_food_records(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS normalization_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalization_run_id TEXT NOT NULL REFERENCES normalization_runs(id) ON DELETE CASCADE,
    raw_food_record_id BIGINT REFERENCES raw_food_records(id) ON DELETE CASCADE,
    issue_code TEXT NOT NULL,
    severity TEXT NOT NULL CHECK(severity IN ('info','warning','error')),
    field_name TEXT,
    message TEXT NOT NULL,
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_normalization_issues_run ON normalization_issues(normalization_run_id, issue_code);

CREATE TABLE IF NOT EXISTS agent_jobs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id TEXT REFERENCES child_profiles(id) ON DELETE CASCADE,
    job_type TEXT NOT NULL CHECK(job_type IN ('onboarding_summary','measurement_followup','question_answer','daily_followup')),
    trigger TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL CHECK(status IN ('queued','running','completed','failed','blocked')),
    attempts BIGINT NOT NULL DEFAULT 0 CHECK(attempts >= 0),
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    completed_at TEXT,
    error TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_claim ON agent_jobs(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_user ON agent_jobs(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_runs (
    id TEXT PRIMARY KEY,
    job_id TEXT REFERENCES agent_jobs(id) ON DELETE SET NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id TEXT REFERENCES child_profiles(id) ON DELETE SET NULL,
    correlation_id TEXT NOT NULL,
    trigger TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('running','completed','failed','blocked')),
    model TEXT NOT NULL,
    policy_version TEXT NOT NULL,
    source_version TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    error TEXT,
    structured_output_json TEXT
);
CREATE INDEX IF NOT EXISTS idx_agent_runs_user ON agent_runs(user_id, started_at DESC);

CREATE TABLE IF NOT EXISTS agent_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    sequence_no BIGINT NOT NULL CHECK(sequence_no >= 1),
    stage TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('running','completed','failed','blocked','skipped')),
    input_json TEXT NOT NULL,
    output_json TEXT,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    error TEXT,
    UNIQUE(run_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS agent_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL CHECK(action_type IN ('answer','record_summary','queue_followup','external_delivery','blocked')),
    status TEXT NOT NULL CHECK(status IN ('proposed','approved','executed','blocked','failed')),
    payload_json TEXT NOT NULL,
    policy_reason TEXT NOT NULL,
    created_at TEXT NOT NULL,
    executed_at TEXT
);

CREATE TABLE IF NOT EXISTS schedules (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id TEXT REFERENCES child_profiles(id) ON DELETE CASCADE,
    schedule_type TEXT NOT NULL CHECK(schedule_type IN ('daily_followup')),
    local_time TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Asia/Jakarta',
    enabled BIGINT NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),
    next_run_at TEXT NOT NULL,
    last_run_at TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_schedules_due ON schedules(enabled, next_run_at);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    actor_type TEXT NOT NULL CHECK(actor_type IN ('user','agent','telegram','system')),
    event_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    correlation_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_user_time ON audit_events(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS inbound_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_event_id TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    received_at TEXT NOT NULL,
    processed_at TEXT,
    status TEXT NOT NULL CHECK(status IN ('received','processed','ignored','failed')),
    error TEXT,
    UNIQUE(provider, provider_event_id)
);

CREATE TABLE IF NOT EXISTS outbound_messages (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    channel_identity_id BIGINT REFERENCES channel_identities(id) ON DELETE SET NULL,
    run_id TEXT REFERENCES agent_runs(id) ON DELETE SET NULL,
    chat_id TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('queued','sent','failed','skipped_unconfigured')),
    provider_message_id TEXT,
    response_json TEXT,
    error TEXT,
    created_at TEXT NOT NULL,
    sent_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_outbound_status ON outbound_messages(status, created_at);



CREATE OR REPLACE FUNCTION nutrishield_check_child_owner() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.child_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM child_profiles WHERE id=NEW.child_id AND user_id=NEW.user_id) THEN
    RAISE EXCEPTION 'child ownership mismatch';
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS consents_child_owner ON consents;
CREATE TRIGGER consents_child_owner BEFORE INSERT OR UPDATE ON consents FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();
DROP TRIGGER IF EXISTS jobs_child_owner ON agent_jobs;
CREATE TRIGGER jobs_child_owner BEFORE INSERT OR UPDATE ON agent_jobs FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();
DROP TRIGGER IF EXISTS runs_child_owner ON agent_runs;
CREATE TRIGGER runs_child_owner BEFORE INSERT OR UPDATE ON agent_runs FOR EACH ROW EXECUTE FUNCTION nutrishield_check_child_owner();

CREATE INDEX IF NOT EXISTS idx_food_search_name ON canonical_foods USING gin (to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(normalized_name,'')));
